#!/usr/bin/env bash
# Configure your domain
display_info ()
{
    domain="$1"
    subdomain="$2"
    dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION:' | sed '1d' | awk -v var="$subdomain" '{printf "The subdomain %s is a %s record and points to %s\n", var, $4, $5}' 
}

for subdomain in "www" "lb-01" "web-01" "web-02"
do
    if [ -z "$2" ] || [ "$2" == "$subdomain" ] ;
    then
	display_info "$1" "$subdomain"
    fi
done

