#!/usr/bin/env bash
# script that transfers a file from our client to a server
# Accepts four arguments

ARGC="$#"

if [[ "$ARGC" -lt 4 ]]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -i "$4" -o Stricthostkeychecking=no "$1" "$3"@"$2":~
fi
