#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy

sudo chown -R ubuntu /etc/haproxy

configuration="\
frontend http
	bind *:80
	mode http
	default_backend web-server
backend web-server
	balance roundrobin
	server 4575-web-01 54.234.152.4 check
	server 4575-web-02 18.207.125.199 check
"

sudo echo "$configuration" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart

