#!/usr/bin/env bash
#script that displays numbers from 1 to 100
for x in {1..100}
do
	if [ $(( x % 3 )) == 0 ]
	then
		if [ $(( x % 5)) == 0 ]
		then
			echo "FizzBuzz"
		else
			echo "Fizz"
		fi
	elif [ $(( x % 5 )) == 0 ]
	then
		echo "Buzz"
	else
		echo "$x"
	fi
done