#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

y=1

while [ $y -le 10 ]
do
	if [[ $y -eq 4 ]]
	then
		echo "bad luck"
	elif [[ $y -eq 8 ]]
	then
		echo "good luck"
	else 
		echo "Best School"
	fi
y=$((y + 1))
done