#!/usr/bin/env bash
# script that displays numbers from 1 to 20
y=1

while ((y<=20))
do
	echo "$y"
	case $y in
	4)
		echo "bad luck from China"
	;;
	9)
		echo "bad luck from Japan"
	;;
	17)
		echo "bad luck from Italy"
	;;
	esac
	y=$((y+1))
done